apiVersion: apps/v1
kind: Deployment
metadata:
  name: sendpix-deployment
  namespace: camshare
spec:
  selector:
    matchLabels:
      app: envhat
  replicas: 1
  template:
    metadata:
      labels:
        app: envhat
    spec:
      containers:
      - name: envhat
        image: quay.io/kproche0/sendpix:meye.stable
        imagePullPolicy: Always
        #command: ["/bin/bash","-c","sleep infinity"]
        securityContext:
          privileged: true
        env:
          - name: WebSocketURL
            value: "wss://edgepilognodered2021.mybluemix.net/ws/chat"
          - name: VideoSource
            value: "/dev/video0"
          - name: ImageUploadURL
            value: "http://edgepilognodered2021.mybluemix.net/upload"
          - name: CameraAngle
            value: "0"
          - name: TZ
            value: "America/Los_Angeles"
          - name: CPUTF
            value: "1.5558"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        ports:
        - containerPort: 8088
        # resource required for hpa
        resources:
          requests:
            memory: 128M
            cpu: 125m
          limits:
            memory: 1024M
            cpu: 1000m
      hostAliases:
      - hostnames:
        - edgepilognodered2021.mybluemix.net
        ip: 169.62.254.79
---
apiVersion: v1
kind: Service
metadata:
 name: sendpix-svc
 namespace: camshare
 labels:
   app: envhat
spec:
 type: NodePort
 ports:
 - port: 8088
   nodePort: 30088
 selector:
   app: envhat

